CREATE TABLE [dbo].[Customers]
(
		CustomerID INT IDENTITY(1,1) PRIMARY KEY,
		FirstName NVARCHAR(100) NOT NULL,
		LastName NVARCHAR(100) NOT NULL,
		Email NVARCHAR(255) NULL,
		Phone NVARCHAR(50) NULL,
		AddressLine1 NVARCHAR(250) NULL,
		AddressLine2 NVARCHAR(250) NULL,
		City NVARCHAR(100) NULL,
		State NVARCHAR(100) NULL,
		PostalCode NVARCHAR(20) NULL,
		Country NVARCHAR(100) NULL,		CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
)
