CREATE TABLE [dbo].[Orders]
(
		OrderID INT IDENTITY(1,1) PRIMARY KEY,
		OrderNumber NVARCHAR(50) NOT NULL UNIQUE,
		CustomerID INT NOT NULL REFERENCES [dbo].[Customers](CustomerID) ON DELETE NO ACTION,
		OrderDate DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
		Status NVARCHAR(50) NOT NULL DEFAULT 'New',
		ShippingAddress NVARCHAR(500) NULL,
		TotalAmount DECIMAL(18,4) NOT NULL DEFAULT(0.00)
)
