CREATE TABLE [dbo].[ProductPricing]
(
		PricingID INT IDENTITY(1,1) PRIMARY KEY,
		ProductID INT NOT NULL REFERENCES [dbo].[Products](ProductID) ON DELETE CASCADE,
		Price DECIMAL(18,4) NOT NULL,
		Currency NVARCHAR(3) NOT NULL DEFAULT 'USD',
		StartDate DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
		EndDate DATETIME2 NULL,
		IsCurrent AS (CASE WHEN EndDate IS NULL THEN 1 ELSE 0 END) PERSISTED
)
