CREATE TABLE [dbo].[Products]
(
		ProductID INT IDENTITY(1,1) PRIMARY KEY,
		SKU NVARCHAR(50) NOT NULL UNIQUE,
		Name NVARCHAR(200) NOT NULL,
		Description NVARCHAR(MAX) NULL,
		Category NVARCHAR(100) NULL,
		IsActive BIT NOT NULL DEFAULT(1),
		CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
)
